### ISSUE TITLE
Sprint 0 Update

### ISSUE THREAD

**Issue by tianyan-zhu** [shizuko-akamoto/Trecipe#31]

**Comment by shumalll** [comment]
Scrum Update - k7y0b

- What you’ve worked on in the previous two weeks
  - We spent most of the time on project planning, which includes defining the scope of our project and dicsussing the requirements.

- What you’ll be working on in the next two weeks
  - I will be working on setting up the logic for uploading photo locally, and the frontend for context filter

- Where you might have gotten stuck during the last two weeks.
  - Maybe in deciding which functionalities should be minimal and which ones are not. It was slightly harder to decide but eventually we agreed on focusing on frontend with single user first.

**Comment by tianyan-zhu** [comment]
Changed to **Sprint 0 from 1**, since it is reflecting on things we have done in the previous 2 weeks. The upcoming one is Sprint 1.

**Comment by shizuko-akamoto** [comment]
Scrum update - z8c1b

- What you’ve worked on in the previous two weeks
These two weeks, I mostly participated in the group discussions on deciding the requirements and general workflow of the web app, and produced rough sketches of those workflow.

- What you’ll be working on in the next two weeks
I will be responsible for producing UX mocks for the Trecipe cards page we are aiming to complete this upcoming sprint, and then for the latter half of the sprint, will switch to implementing front end for two components: navigation bar and add button (that brings up a popup window).

- Where you might have gotten stuck during the last two weeks.
In general, our discussion for the scope of our project went pretty smoothly, but I felt particularly challenging to nail down the specifics when trying to break down our two minimal requirements. Perhaps because we havn't covered databases and backend pieces in lecture, but thinking about what work needs to be completed for backend was difficult.

**Comment by tianyan-zhu** [comment]
Migrating the update to #32
